import React from 'react';
import { Product, Category } from './types';
import { 
  Car, 
  Baby, 
  Shirt, 
  Monitor, 
  Headphones, 
  Clapperboard, 
  ShoppingBasket, 
  HeartPulse, 
  Utensils, 
  Wrench, 
  Tent, 
  Plane, 
  Gamepad2, 
  MoreHorizontal 
} from 'lucide-react';

export const CATEGORIES: Category[] = [
  { id: 'auto', name: 'Automotive & Motorcycles', icon: <Car size={20} /> },
  { id: 'baby', name: 'Babies & Kids', icon: <Baby size={20} /> },
  { id: 'fashion', name: 'Clothing & Accessories', icon: <Shirt size={20} /> },
  { id: 'tech', name: 'Computers & Mobile', icon: <Monitor size={20} /> },
  { id: 'electronics', name: 'Electronics & Appliances', icon: <Headphones size={20} /> },
  { id: 'movies', name: 'Entertainment & Movies', icon: <Clapperboard size={20} /> },
  { id: 'grocery', name: 'Groceries', icon: <ShoppingBasket size={20} /> },
  { id: 'beauty', name: 'Health & Beauty', icon: <HeartPulse size={20} /> },
  { id: 'food', name: 'Restaurant', icon: <Utensils size={20} /> },
  { id: 'services', name: 'Services', icon: <Wrench size={20} /> },
  { id: 'outdoor', name: 'Sporting & Outdoor', icon: <Tent size={20} /> },
  { id: 'travel', name: 'Travel & Leisure', icon: <Plane size={20} /> },
  { id: 'gaming', name: 'Video Games & Gaming', icon: <Gamepad2 size={20} /> },
  { id: 'others', name: 'Others', icon: <MoreHorizontal size={20} /> },
];

export const POPULAR_PERKS: Product[] = [
  {
    id: '1',
    title: 'Winter in KOREA (5D4N)',
    category: 'Travel & Leisure',
    price: 42888,
    originalPrice: 46388,
    image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?q=80&w=2070&auto=format&fit=crop',
    rating: 4.9,
    reviews: 342,
    isHot: true,
    merchant: 'StrideFlyer Travel and Tours',
  },
  {
    id: '2',
    title: 'Buy 3 CAPTAIN MAJOR & 1.5L Coke',
    category: 'Restaurant',
    price: 447,
    originalPrice: 566,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1981&auto=format&fit=crop',
    rating: 4.7,
    reviews: 128,
    merchant: 'Captain Philippines Pizza',
  },
  {
    id: '3',
    title: 'K570.3 H4 LED Headlight 5% Off',
    category: 'Automotive & Motorcycles',
    price: 7351,
    originalPrice: 8370,
    image: 'https://images.unsplash.com/photo-1486006920555-c77dcf18193c?q=80&w=2056&auto=format&fit=crop',
    rating: 4.5,
    reviews: 56,
    isNew: true,
    merchant: 'Keon Sondra Corporation',
  },
  {
    id: '4',
    title: 'Ferdie Salon Premium Treatment',
    category: 'Health & Beauty',
    price: 950,
    originalPrice: 1400,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=2069&auto=format&fit=crop',
    rating: 4.8,
    reviews: 890,
    merchant: 'Ferdie Ilagan Salon & Spa',
  },
  {
    id: '5',
    title: '50% OFF on Lift & Contour',
    category: 'Health & Beauty',
    price: 35000,
    originalPrice: 70000,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=2070&auto=format&fit=crop',
    rating: 5.0,
    reviews: 12,
    merchant: 'The Vibe Holistic Medical Aesthetics',
  },
  {
    id: '6',
    title: 'BUY MAJOR OR COLONEL',
    category: 'Restaurant',
    price: 139,
    originalPrice: 149,
    image: 'https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?q=80&w=2070&auto=format&fit=crop',
    rating: 4.2,
    reviews: 45,
    merchant: 'Captain Philippines Pizza',
  },
  {
      id: '7',
      title: 'K570.3 H11 LED Headlight',
      category: 'Automotive & Motorcycles',
      price: 7695,
      originalPrice: 8100,
      image: 'https://images.unsplash.com/photo-1503376763036-066120622c74?q=80&w=2070&auto=format&fit=crop',
      rating: 4.6,
      reviews: 23,
      merchant: 'Keon Sondra Corporation',
  }
];

export const DAILY_DROPS: Product[] = [
  {
    id: '8',
    title: 'K570.3 HB3 5% Off',
    category: 'Automotive & Motorcycles',
    price: 7695,
    originalPrice: 8100,
    image: 'https://images.unsplash.com/photo-1619550798150-1e5828c6df32?q=80&w=2070&auto=format&fit=crop',
    rating: 4.9,
    reviews: 10,
    isHot: true,
    merchant: 'Keon Sondra Corporation',
  },
  {
    id: '9',
    title: 'K570.3 HB4 5% Off',
    category: 'Automotive & Motorcycles',
    price: 7695,
    originalPrice: 8100,
    image: 'https://images.unsplash.com/photo-1552857096-724d275727e0?q=80&w=1974&auto=format&fit=crop',
    rating: 4.8,
    reviews: 8,
    merchant: 'Keon Sondra Corporation',
  }
];